#!/usr/bin/env node
/**
 * build-css.js — concatenates each page's modular CSS source into a single
 * minified bundle, eliminating render-blocking sequential @import requests.
 *
 * Source of truth:  src/css/main-<page>.css  (+ src/css/blocks/*.css)  — not deployed
 * Output (generated): public/css/<bundle>.css  — committed + served
 *
 * Run:  npm run build:css
 * Never hand-edit the generated *.bundle.css files — edit the source and rebuild.
 */
'use strict';

const fs = require('fs');
const path = require('path');

const srcDir = path.join(__dirname, '..', 'src', 'css');
const outDir = path.join(__dirname, '..', 'public', 'css');

/** entry source -> generated bundle */
const PAGES = {
  'main-home.css': 'styles.bundle.css',
  'main-services.css': 'services.bundle.css',
  'main-mailboxes.css': 'mailboxes.bundle.css',
  'main-print.css': 'print.bundle.css',
};

/** Inline @import url("blocks/x.css") with the referenced file's contents. */
function inlineImports(entryPath) {
  const dir = path.dirname(entryPath);
  const text = fs.readFileSync(entryPath, 'utf8');
  return text.replace(
    /@import\s+url\(\s*["']?([^"')]+)["']?\s*\)\s*;?/g,
    (_match, ref) => {
      const target = path.join(dir, ref);
      if (!fs.existsSync(target)) {
        throw new Error(`Missing @import target: ${ref} (in ${path.basename(entryPath)})`);
      }
      return `\n/* ${ref} */\n${fs.readFileSync(target, 'utf8')}\n`;
    }
  );
}

/** Conservative minify: safe for calc()/combinators; only strips clearly-redundant bytes. */
function minify(css) {
  return css
    .replace(/\/\*[\s\S]*?\*\//g, '') // comments
    .replace(/\s+/g, ' ') // collapse whitespace
    .replace(/\s*([{};,])\s*/g, '$1') // trim around { } ; ,
    .replace(/;\}/g, '}') // drop last semicolon in a block
    .replace(/\}\s+/g, '}') // tidy after }
    .trim();
}

const banner =
  '/* AUTO-GENERATED by scripts/build-css.js — DO NOT EDIT. ' +
  'Edit css/main-*.css and css/blocks/*.css, then run: npm run build:css */\n';

let count = 0;
for (const [entry, bundle] of Object.entries(PAGES)) {
  const entryPath = path.join(srcDir, entry);
  const bundlePath = path.join(outDir, bundle);
  if (!fs.existsSync(entryPath)) {
    console.warn(`skip: ${entry} not found`);
    continue;
  }
  const out = banner + minify(inlineImports(entryPath)) + '\n';
  fs.writeFileSync(bundlePath, out, 'utf8');
  console.log(`built ${bundle}  (${(out.length / 1024).toFixed(1)} KB)  <- ${entry}`);
  count++;
}
console.log(`\nDone. ${count} bundle(s) generated.`);
