#!/usr/bin/env node
/**
 * scripts/build-css.js
 * ====================
 * CSS bundler: concatenates modular CSS source into production bundles.
 *
 * PURPOSE:
 * - Reads source CSS from src/css/main-*.css files
 * - Inlines all @import url("blocks/*.css") references
 * - Minifies output (removes comments, collapses whitespace)
 * - Writes bundled CSS to public/css/*.bundle.css
 * - Idempotent: safe to run multiple times
 *
 * BUILD FLOW:
 * 1. Read main-home.css → inline blocks/ imports → minify → write styles.bundle.css
 * 2. Read main-services.css → inline blocks/ imports → minify → write services.bundle.css
 * 3. Read main-mailboxes.css → inline blocks/ imports → minify → write mailboxes.bundle.css
 * 4. Read main-print.css → inline blocks/ imports → minify → write print.bundle.css
 *
 * WHY THIS APPROACH?
 * - Eliminates render-blocking @import chains (performance win)
 * - Keeps source files modular (maintainability)
 * - Bundles are generated, not committed (single source of truth)
 * - Minification reduces file size
 *
 * RUNNING:
 * - npm run build:css
 * - Run this whenever you edit files in src/css/
 *
 * IMPORTANT:
 * - NEVER edit public/css/*.bundle.css directly
 * - Always edit source files in src/css/ and rebuild
 * - If imports are missing, the build will throw an error
 *
 * DEPENDENCIES:
 * - fs (Node built-in)
 * - path (Node built-in)
 */
'use strict';

const fs = require('fs');
const path = require('path');

const srcDir = path.join(__dirname, '..', 'src', 'css');
const outDir = path.join(__dirname, '..', 'public', 'css');

function readCssFile(filePath) {
  return fs.readFileSync(filePath, 'utf8').replace(/\*\/\\n(?=\/\*)/g, '*/\n');
}

/** entry source -> generated bundle */
const PAGES = {
  'main-home.css': 'styles.bundle.css',
  'main-services.css': 'services.bundle.css',
  'main-mailboxes.css': 'mailboxes.bundle.css',
  'main-print.css': 'print.bundle.css',
};

/** Inline @import url("blocks/x.css") with the referenced file's contents. */
function inlineImports(entryPath) {
  const dir = path.dirname(entryPath);
  const text = readCssFile(entryPath);
  return text.replace(
    /@import\s+url\(\s*["']?([^"')]+)["']?\s*\)\s*;?/g,
    (_match, ref) => {
      const target = path.join(dir, ref);
      if (!fs.existsSync(target)) {
        throw new Error(`Missing @import target: ${ref} (in ${path.basename(entryPath)})`);
      }
      return `\n/* ${ref} */\n${readCssFile(target)}\n`;
    }
  );
}

/** Conservative minify: safe for calc()/combinators; only strips clearly-redundant bytes. */
function minify(css) {
  return css
    .replace(/\/\*[\s\S]*?\*\//g, '') // comments
    .replace(/\s+/g, ' ') // collapse whitespace
    .replace(/\s*([{};,])\s*/g, '$1') // trim around { } ; ,
    .replace(/;\}/g, '}') // drop last semicolon in a block
    .replace(/\}\s+/g, '}') // tidy after }
    .trim();
}

const banner =
  '/* AUTO-GENERATED by scripts/build-css.js — DO NOT EDIT. ' +
  'Edit css/main-*.css and css/blocks/*.css, then run: npm run build:css */\n';

let count = 0;
for (const [entry, bundle] of Object.entries(PAGES)) {
  const entryPath = path.join(srcDir, entry);
  const bundlePath = path.join(outDir, bundle);
  if (!fs.existsSync(entryPath)) {
    console.warn(`skip: ${entry} not found`);
    continue;
  }
  const out = banner + minify(inlineImports(entryPath)) + '\n';
  fs.writeFileSync(bundlePath, out, 'utf8');
  console.log(`built ${bundle}  (${(out.length / 1024).toFixed(1)} KB)  <- ${entry}`);
  count++;
}
console.log(`\nDone. ${count} bundle(s) generated.`);
